# Generated by Django 5.1.4 on 2024-12-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_orders_customer_orders_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
